language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - nightly

install:
    - composer install

after_success:
    - chmod 600 .travis/deploy_key.pem
    - ssh-add .travis/deploy_key.pem
    - git config --global user.name ideatobot
    - git config --global user.email info@ideato.it
    - ./bin/build.sh

notifications:
    slack: ideato:IbCCcq5XKF1Aa23xfDNa2uOS
    email:
        - nb@ideato.it
        - sd@ideato.it
