language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - nightly

before_install:
    - openssl aes-256-cbc -K $encrypted_9c790549322a_key -iv $encrypted_9c790549322a_iv -in bin/.travis/travis.pem.enc -out ~/.ssh/id_rsa -d

install:
    - composer install

script: phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
    - chmod 600 ~/.ssh/id_rsa
    - eval `ssh-agent -s`
    - ssh-add ~/.ssh/id_rsa
    - git config --global user.name ideatobot
    - git config --global user.email info@ideato.it
    - git clone --depth=50 --branch=gh-pages git@github.com:ideatosrl/vagrun.git /tmp/vagrun
    - ./bin/build.sh

notifications:
    slack: ideato:IbCCcq5XKF1Aa23xfDNa2uOS
    email:
        - nb@ideato.it
        - sd@ideato.it
